# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "e1c4c694f669f235050aa73c20600f68"
application_url = "https://tahoe-creative-detector-conducting.trycloudflare.com"
embedded = true
name = "seo-wizzard-stage "
handle = "seo-wizzard-stage"

[build]
automatically_update_urls_on_dev = true
include_config_on_deploy = true

[webhooks]
api_version = "2025-04"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_themes,write_online_store_navigation"

[auth]
redirect_urls = [
  "https://tahoe-creative-detector-conducting.trycloudflare.com/auth/callback",
  "https://tahoe-creative-detector-conducting.trycloudflare.com/auth/shopify/callback",
  "https://tahoe-creative-detector-conducting.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false
